### ISSUE TITLE
Proposed API and build improvements

### ISSUE THREAD

**Issue by bz2** [GoogleCloudPlatform/stackdriver-errors-js#45]
Thanks for publishing this library, have been using it a quite heavily over the last few months to record frontend errors in the same place as we track backend problems. Out of this, I'd like to submit some improvements, some of which may require some discussion and decisions, so this is a meta issue for tracking the proposed changes.

## Library API

Currently `StackdriverErrorReporter` exposes a `callback` parameter in a few places, mostly to enable the testing. This allows some errors to be seen by callers, but does not expose the extracted stacktrace message and is somewhat awkward to use. As [stacktrace-js](https://github.com/stacktracejs/stacktrace.js) already uses promises, I suggest the interface here should too. The [promise api is widely available](https://caniuse.com/#feat=promises) and there's a polyfill bundled in the build already (though this may want some tweaking, see below).

- [ ] Return a Promise from `report()` and `sendErrorPayload()`
- [ ] Propagate `payload` (or just `payload.message`) when promise is fulfilled
- [ ] Add config option to output message to `console.log` #6  
- [ ] Handle non-200 HTTP responses #32 

When calling `report()` directly from a logging framework, stacktraces for strings currently start inside the logger rather than at the caller.

- [ ] Expose `firstFrameIndex` as an argument to `report()`

## Build and packaging

This is a simple library and doesn't need a complicated build, but there are a few niggles currently when embedding in a modern webapp, and the single file bundle could also been improved. Not sure how far to go on this front, but there are some simple improvements to make at least.

- [ ] Update devDependencies to latest versions
- [ ] Remove 'dist' folder from version control
- [ ] Make `npm start` launch the demo in a browser window
- [ ] Enable ES6 import without hack #2

**Comment by steren** [comment]
Thanks for your contributions. They look good to me.
I will be reviewing the changes within the next days.

**Comment by bz2** [comment]
Thank you very much for review and landing so far!

Will put the next batch up for consideration later.

Main things to resolve are what specifically 'report()' should resolve and reject into, and how to produce both a simple ES5 compatible bundled file and a clean module interface.

**Comment by steren** [comment]
I created a new release with all your existing improvements. 

Thanks a lot for your contributions!

**Comment by bz2** [comment]
@steren Thanks! Will update our code to use latest version and some of the new interfaces.
